:hivemq-link: http://www.hivemq.com
:hivemq-extension-docs-link: https://www.hivemq.com/docs/kafka/latest/enterprise-extension-for-kafka/kafka.html#customization
:hivemq-extension-docs-archetype-link: https://www.hivemq.com/docs/extensions/latest/#maven-archetype-chapter
:hivemq-blog-tools: http://www.hivemq.com/mqtt-toolbox
:maven-documentation-profile-link: http://maven.apache.org/guides/introduction/introduction-to-profiles.html
:hivemq-support: https://community.hivemq.com/
:hivemq-testcontainer: https://github.com/hivemq/hivemq-testcontainer
:hivemq-mqtt-client: https://github.com/hivemq/hivemq-mqtt-client

== HiveMQ Kafka Extension Hello World Customization

*Type*: Demonstration Customization

*Version*: 4.4.0

*License*: Apache License Version 2.0

=== Purpose

This Hello World customizations uses a Mqtt-to-Kafka transformer which forwards MQTT PUBLISHES to a Kafka cluster.
It maps the MQTT topic structure to a matching Kafka topic structure and preserves MQTT 4 user properties as Kafka record headers.

We strongly recommend reading the {hivemq-extension-docs-link}[HiveMQ Extension Documentation]
to grasp the core concepts of HiveMQ Kafka customization development.

=== Installation

. Clone this repository into a Java 11 gradle project.
. Run `./gradlew jar` task from gradle to build the customization.
. Move the file: "build/libs/hivemq-kafka-hello-world-customization-4.4.0.jar" to the directory: "HIVEMQ_HOME/extensions/hivemq-kafka-extension/customizations"
. Copy the resources/kafka-configuration.xml to "HIVEMQ_HOME/extensions/hivemq-kafka-extension" and adapt it to your environment.
. Delete the "HIVEMQ_HOME/extensions/hivemq-kafka-extension/DISABLED" file.
. Start HiveMQ.

=== First Steps

==== Manual Testing

Connect with an {hivemq-blog-tools}[MQTT client] of your choice.
Publish a MQTT message to the topic _transform/customization_.
Monitor your Kafka cluster for a record from topic _transform.customization_.

=== Next steps

Awesome, you got your first HiveMQ Kafka customization working.

Now read the {hivemq-extension-docs-link}[HiveMQ Kafka Extension Customization Documentation] to see what customizations can do.

=== Need help?

If you encounter any problems, we are happy to help.
The best place to get in contact is our {hivemq-support}[cmmunity forum].

= License

HiveMQ Hello World Extension is licensed under the `APACHE LICENSE, VERSION 2.0`.
A copy of the license can be found link:LICENSE[here].